---

servicio: '{% if ansible_os_family == "Debian" %}apache2{% else %}httpd{% endif %}'



paquetes: '{% if ansible_os_family == "Debian" %}{{ paquetes_debian }}{% else %}{{ paquetes_redhat }}{% endif %}'



paquetes_debian:
  - php
  - php-cli
  - php-common
  - php-dev
  - php-pear
  - php-gd
  - php-mbstring
  - php-mysql
  - php-xml
  - php-bcmath
  - libapache2-mod-php

paquetes_redhat:
  - php82
  - php82-php-cli
  - php82-php-common
  - php82-php-pear
  - php82-php-gd
  - php82-php-mbstring
  - php82-php-xml
  - php82-php-bcmath
  - php82-php-mysqlnd


...