---

- name: Incluir fichero vault.yml
  ansible.builtin.include_vars:
    file: vault.yml


- name: A単adir repositorio Zabbix y epel en RedHat
  block:
  - name: A単adir repo Epel
    ansible.builtin.yum:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
      state: present
      disable_gpg_check: true

  - name: Instalar repositorio Zabbix Rhel
    ansible.builtin.yum_repository:
      name: Centos8_Zabbix
      description: Centos8 Zabbix
      baseurl: https://repo.zabbix.com/zabbix/6.4/rhel/8/x86_64/
      gpgcheck: no
  when: ansible_os_family == "RedHat"


- name: A単adir repositorio Zabbix en Debian
  block:
  - name: Instalar gnupg
    ansible.builtin.apt:
      name: gnupg
      state: present
      update_cache: true

  - name: Agregar clave GPG de Zabbix Debian
    ansible.builtin.apt_key:
      url: https://repo.zabbix.com/zabbix-official-repo.key
      state: present

  - name: A単adir repositorio Zabbix Debian
    ansible.builtin.apt_repository:
      repo: deb https://repo.zabbix.com/zabbix/6.4/debian/ {{ ansible_distribution_release }} main
      state: present
  when: ansible_distribution == "Debian"


- name: Instalar zabbix
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ paquetes }}"


- name: Importar db zabbix
  shell:
    cmd: "zcat /usr/share/zabbix-sql-scripts/mysql/server.sql.gz | mysql -u {{ db_user }} -p{{ db_password }} -D {{ db_name }}"
  changed_when: false


- name: Configuracion Zabbix
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_server.conf
    line: "DBPassword={{ db_password }}"


- name: Configuracion PHP para web Zabbix
  ansible.builtin.lineinfile:
    path: "{{ path_php }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {
      regexp: "^post_max_size",
      line: "post_max_size = 16M"      
    }
    - {
      regexp: "^max_execution_time",
      line: "max_execution_time = 300"      
    }
    - {
      regexp: "^max_input_time",
      line: "max_input_time = 300"      
    }    
  notify: Reiniciar PHP

- name: Crear enlace simbolico para web zabbix
  ansible.builtin.file:
    src: /usr/share/zabbix
    dest: /var/www/html/zabbix
    state: link


- name: Levantar servicios Zabbix
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - zabbix-server
    - zabbix-agent


...