---

- name: Incluir fichero vault.yml
  ansible.builtin.include_vars:
    file: vault.yml


- name: Añadir repositorio Zabbix en RedHat
  when: ansible_os_family == "RedHat"
  block:
  - name: Instalar repositorio Zabbix Rhel
    ansible.builtin.yum_repository:
      name: Zabbix
      description: Zabbix
      baseurl: https://repo.zabbix.com/zabbix/6.4/rhel/8/x86_64/
      gpgcheck: no


- name: Añadir repositorio Zabbix en Debian
  when: ansible_distribution == "Debian"
  block:
  - name: Instalar gnupg
    ansible.builtin.apt:
      name: gnupg
      state: present
      update_cache: true

  - name: Agregar clave GPG de Zabbix Debian
    ansible.builtin.apt_key:
      url: https://repo.zabbix.com/zabbix-official-repo.key
      state: present

  - name: Añadir repositorio Zabbix Debian
    ansible.builtin.apt_repository:
      repo: deb https://repo.zabbix.com/zabbix/6.4/debian/ {{ ansible_distribution_release }} main
      state: present


- name: Instalar zabbix
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ paquetes }}"


- name: Importar db zabbix
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    state: import
    force: true
    encoding: utf8mb4
    target: /usr/share/zabbix-sql-scripts/mysql/server.sql.gz
    login_unix_socket: "{{ login_socket }}"
  changed_when: false


- name: Configuracion Zabbix
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_server.conf
    regexp: "^DBPassword="
    insertafter: "^# DBPassword"
    line: "DBPassword={{ db_password }}"


- name: Configuracion PHP para web Zabbix
  ansible.builtin.lineinfile:
    path: "{{ path_php }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {
      regexp: "^post_max_size",
      line: "post_max_size = 16M"      
    }
    - {
      regexp: "^max_execution_time",
      line: "max_execution_time = 300"      
    }
    - {
      regexp: "^max_input_time",
      line: "max_input_time = 301"      
    }    
  notify: Reiniciar PHP


- name: Crear enlace simbolico para web zabbix
  ansible.builtin.file:
    src: /usr/share/zabbix
    dest: /var/www/html/zabbix
    state: link


- name: Levantar servicios Zabbix
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - zabbix-server
    - zabbix-agent

...